version: '3'
services:
  corona-grabber:
    container_name: corona-grabber
    build: .
    volumes:
      - corona-data:/data
    #network_mode: host
    #ports:
    #  - "1880:1880"
    #  - "5353:5353"
    #  - "51826:51826"
    restart: always
  lighttpd:
    image: sebp/lighttpd
    volumes:
      - corona-data:/var/www/localhost/htdocs
    ports:
      - "90:80"
    tty: true
    restart: always
volumes:
  corona-data:
